<?php

/**
 * @file
 * User Profile Picture overrides.
 */

 /**
  * implement hook_user
  * 
  */
function user_avatar_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  
  if($op == 'submit') {
    dsm($edit,'Submit');
    //picture is being added/updated
    if(!empty($edit['picture'])) {
      $cachbuster = time();
      
      //check for existing entry
      db_query("SELECT uid from {user_avatar} WHERE uid=%d", $user_uid);
      if(db_affected_rows() > 0) {
        //update
        db_query("UPDATE {user_avatar} SET uid=%d, timestamp=%d where uid=%d",$user_uid,$cachbuster,$user_uid);
      } else {
        //insert
        db_query("INSERT INTO {user_avatar} (uid,timestamp) VALUES (%d,%d)",$user_uid,$cachbuster);
      }
      
    }
     //deleting user picture
    if($edit['picture_delete'] == 1) {
      $result = db_query("DELETE FROM {user_avatar} where uid=%d",$user_uid); 
    }
    
  }//if $op == 'submit'
    
}//function

function user_avatar_theme_image($path, $alt = '', $title = '', $attributes = NULL, $getsize = TRUE) {
  dsm($path);
   if (!$getsize || (is_file($path) && (list($width, $height, $type, $image_attributes) = @getimagesize($path)))) {
    $attributes = drupal_attributes($attributes);
    $url = (url($path) == $path) ? $path : (base_path() . $path);
    return '<img src="' . check_url($url) . '" alt="' . check_plain($alt) . '" title="' . check_plain($title) . '" ' . (isset($image_attributes) ? $image_attributes : '') . $attributes . ' />';
  }
}

function user_avatar_preprocess_user_picture(&$variables) {
  global $user;
  
  $variables['picture'] = '';
  if (variable_get('user_pictures', 0)) {
    $account = $variables['account'];
    if (!empty($account->picture) && file_exists($account->picture)) {
      $account->picture = $account->picture . _get_timestamp(); //New code
      $picture = file_create_url($account->picture);
    }
    else if (variable_get('user_picture_default', '')) {
      $picture = variable_get('user_picture_default', '');
    }

    if (isset($picture)) {
      $alt = t("@user's picture", array('@user' => $account->name ? $account->name : variable_get('anonymous', t('Anonymous'))));
      $variables['picture'] = theme('image', $picture, $alt, $alt, '', FALSE);
      if (!empty($account->uid) && user_access('access user profiles')) {
        $attributes = array(
          'attributes' => array('title' => t('View user profile.')),
          'html' => TRUE,
        );
        $variables['picture'] = l($variables['picture'], "user/$account->uid", $attributes);
      }
    }
  }
}

/**
 * advanced_forum module function override
 */
function user_avatar_preprocess_author_pane_user_picture(&$variables) {
  $variables['picture'] = '';
  $account = $variables['account'];

  // Get the imagecache preset, if any.
  $preset = (!empty($variables['picture_preset'])) ? $variables['picture_preset'] : '';

  // If user pictures are enabled...
  if (variable_get('user_pictures', 0)) {
    // Get the user's avatar if they have one or the default picture if exists.
    if (!empty($account->picture) && file_exists($account->picture)) {
      // We only want to get the full URL if not using imagecache.
      $picture = (!empty($preset) && module_exists('imagecache')) ? $account->picture : file_create_url($account->picture);
      $picture = $picture . _get_timestamp();//New code
    }
    elseif (variable_get('user_picture_default', '')) {
      $picture = variable_get('user_picture_default', '');
    }

    // If we have a picture...
    if (isset($picture)) {
      // If there's a preset set and imagecache is enabled...
      if (!empty($preset) && module_exists('imagecache')) {
        // Toss the picture over to imagecache for sizing
        $alt = t("@user's picture", array('@user' => $account->name ? $account->name : variable_get('anonymous', t('Anonymous'))));
        $variables['picture'] = theme('imagecache', $preset, $picture, $alt, $alt);
        $variables['imagecache_used'] = TRUE;
      }
      else {
        // Just run the picture through theme_image. Note that we don't link
        // the picture here since it doesn't make sense for many uses of AP.
        // If the picture needs to be linked, it can be done in the template.
        $alt = t("@user's picture", array('@user' => $account->name ? $account->name : variable_get('anonymous', t('Anonymous'))));
        $variables['picture'] = theme('image', $picture, $alt, $alt, '', FALSE);
        $variables['imagecache_used'] = FALSE;
      }
    }
  }
}

function _get_timestamp() {
  global $user;
  
  $result = db_query("SELECT timestamp FROM {user_avatar} WHERE uid=%d",$user->uid);
  $timestamp = db_fetch_object($result);
  $cachebust = "?" . $timestamp->timestamp;
  return $cachebust;
}